### ISSUE TITLE
Instrukcja uruchomienia PakaWarehouse

### ISSUE THREAD

**Issue by Haseoo** [IUI-januszex/documentation#2]
Opisać jakie są wymagania (wersja pytonga, zależności i jak je zainstalować) oraz polecenia pozwalające uruchomić aplikację i zainicjować bazę.

**Comment by majeklDeSanta** [comment]
To jest potrzebne tylko dla matiego czy dla każdego? Bo mati już sobie
postawił i wszytsko lala

pt., 3 gru 2021, 23:20 użytkownik Dawid Szymkiewicz <
***@***.***> napisał:

**Comment by Haseoo** [comment]
Dla każdego

**Comment by majeklDeSanta** [comment]
Okey

pt., 3 gru 2021, 23:22 użytkownik Dawid Szymkiewicz <
***@***.***> napisał:

**Comment by majeklDeSanta** [comment]
Done
